management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  info:
    git:
      mode: full # Must be full so all fields are present in the git.properties file.

spring:
  jpa:
    hibernate.ddl-auto: create
  datasource:
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: false

springdoc:
  swagger-ui:
    path: /api
