management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  jpa:
    hibernate.ddl-auto: create
  datasource:
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: false

springdoc:
  swagger-ui:
    path: /api
