name: Publish image on Docker Hub

on:
  push:
    branches: [main]
    tags: ['*.*.*']

jobs:
  dockerhub-publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Prepare tags
        id : image_tags
        run: |
           if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="latest,${VERSION}"
           else
            TAGS="snapshot"
           fi
           echo ::set-output name=tags::${TAGS}

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven and publish on Docker Hub with jib
        run: mvn compile -Dgh_login=${{secrets.OPT_DOCKERHUB_LOGIN}} -Dgh_pwd=${{secrets.OPT_DOCKERHUB_PASSWORD}} -Djib.to.tags=${{steps.image_tags.outputs.tags}} jib:build
