name: Publish image on Github Container Registry

on:
  push:
    branches: main

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven and publish with jib
        run: mvn compile -Dlogin=opt_si -Dpassword=${{secrets.OPT_CI_TOKEN}} jib:build -s .github/settings.xml
